# Generated by Django 5.0.5 on 2024-05-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.TextField()),
                ('rating', models.IntegerField()),
                ('comments', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('link', models.URLField()),
            ],
        ),
    ]
