# Generated by Django 5.0.5 on 2024-05-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('Ai', 'Ai'), ('Tech', 'Tech'), ('Python', 'Python'), ('Java', 'Java'), ('C++', 'C++'), ('C#', 'C#'), ('Ruby', 'Ruby'), ('JavaScript', 'JavaScript'), ('React', 'React'), ('Angular', 'Angular'), ('Vue', 'Vue'), ('Django', 'Django'), ('Flask', 'Flask'), ('Express', 'Express'), ('Spring', 'Spring'), ('Laravel', 'Laravel'), ('Node', 'Node'), ('RubyOnRails', 'RubyOnRails'), ('ASP.NET', 'ASP.NET'), ('JQuery', 'JQuery'), ('Bootstrap', 'Bootstrap'), ('Tailwind', 'Tailwind'), ('Materialize', 'Materialize'), ('SemanticUI', 'SemanticUI'), ('Foundation', 'Foundation'), ('Bulma', 'Bulma'), ('UIKit', 'UIKit'), ('AntDesign', 'AntDesign'), ('ChakraUI', 'ChakraUI'), ('Gatsby', 'Gatsby'), ('Next', 'Next'), ('Nuxt', 'Nuxt'), ('Gridsome', 'Gridsome'), ('Svelte', 'Svelte'), ('VuePress', 'VuePress'), ('ReactStatic', 'ReactStatic'), ('Docusaurus', 'Docusaurus'), ('Hugo', 'Hugo'), ('Jekyll', 'Jekyll'), ('Hexo', 'Hexo'), ('Ai', 'Ai'), ('MachineLearning', 'MachineLearning'), ('DeepLearning', 'DeepLearning'), ('DataScience', 'DataScience'), ('BigData', 'BigData'), ('DataAnalysis', 'DataAnalysis'), ('DataEngineering', 'DataEngineering'), ('DataMining', 'DataMining'), ('DataVisualization', 'DataVisualization'), ('BusinessIntelligence', 'BusinessIntelligence'), ('ArtificialIntelligence', 'ArtificialIntelligence'), ('NaturalLanguageProcessing', 'NaturalLanguageProcessing'), ('NaturalLanguageUnderstanding', 'NaturalLanguageUnderstanding'), ('ComputerVision', 'ComputerVision'), ('SpeechRecognition', 'SpeechRecognition'), ('SpeechSynthesis', 'SpeechSynthesis'), ('ReinforcementLearning', 'ReinforcementLearning'), ('Robotics', 'Robotics'), ('ComputerVision', 'ComputerVision'), ('ComputerVision', 'ComputerVision'), ('ComputerVision', 'ComputerVision'), ('ComputerVision', 'ComputerVision'), ('ComputerVision', 'ComputerVision'), ('ComputerVision', 'ComputerVision'), ('ComputerVision', 'ComputerVision'), ('ComputerVision', 'ComputerVision'), ('ComputerVision', 'ComputerVision'), ('ComputerVision', 'ComputerVision'), ('ComputerVision', 'ComputerVision'), ('ComputerVision', 'ComputerVision')], max_length=50),
        ),
    ]
