# Generated by Django 5.0.5 on 2024-05-08 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='news',
            name='rating',
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('Ai', 'Ai'), ('Tech', 'Tech'), ('Python', 'Python'), ('Java', 'Java'), ('C++', 'C++'), ('C#', 'C#'), ('Ruby', 'Ruby'), ('JavaScript', 'JavaScript'), ('React', 'React'), ('Angular', 'Angular'), ('Vue', 'Vue'), ('Django', 'Django'), ('Flask', 'Flask'), ('Express', 'Express'), ('Spring', 'Spring'), ('Laravel', 'Laravel'), ('Node', 'Node'), ('RubyOnRails', 'RubyOnRails'), ('ASP.NET', 'ASP.NET'), ('JQuery', 'JQuery'), ('Bootstrap', 'Bootstrap'), ('Tailwind', 'Tailwind'), ('Materialize', 'Materialize'), ('SemanticUI', 'SemanticUI'), ('Foundation', 'Foundation'), ('Bulma', 'Bulma'), ('UIKit', 'UIKit'), ('AntDesign', 'AntDesign'), ('ChakraUI', 'ChakraUI'), ('Gatsby', 'Gatsby'), ('Next', 'Next'), ('Nuxt', 'Nuxt'), ('Gridsome', 'Gridsome'), ('Svelte', 'Svelte'), ('VuePress', 'VuePress'), ('ReactStatic', 'ReactStatic'), ('Docusaurus', 'Docusaurus'), ('Hugo', 'Hugo'), ('Jekyll', 'Jekyll'), ('Hexo', 'Hexo'), ('Ai', 'Ai'), ('MachineLearning', 'MachineLearning'), ('DeepLearning', 'DeepLearning'), ('DataScience', 'DataScience'), ('BigData', 'BigData'), ('DataAnalysis', 'DataAnalysis'), ('DataEngineering', 'DataEngineering'), ('DataMining', 'DataMining'), ('DataVisualization', 'DataVisualization'), ('BusinessIntelligence', 'BusinessIntelligence'), ('ArtificialIntelligence', 'ArtificialIntelligence'), ('NaturalLanguageProcessing', 'NaturalLanguageProcessing'), ('NaturalLanguageUnderstanding', 'NaturalLanguageUnderstanding'), ('SpeechRecognition', 'SpeechRecognition'), ('SpeechSynthesis', 'SpeechSynthesis'), ('ReinforcementLearning', 'ReinforcementLearning'), ('Robotics', 'Robotics'), ('ComputerVision', 'ComputerVision')], max_length=50),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.news')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='news.news')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
